version: "3"

services:
  # DMZ
  local-dns-soa:
    container_name: local-dns-soa
    hostname: local-dns-soa
    domainname: wt6.ephec-ti.be
    image: docknux/woodytoys-bind
    volumes:
      - ./bind/configFiles/local-dns-soa/etc/named.conf:/etc/bind/named.conf:ro
      - ./bind/configFiles/local-dns-soa/var/db.wt6.ephec-ti.be:/var/bind/db.wt6.ephec-ti.be:ro
      - /srv/docker/bind/logs/local-dns-soa:/var/log/bind:rw
      - /etc/localtime:/etc/localtime:ro
    networks:
      production:
        ipv4_address: 10.40.0.5
    restart: always
  apache-proxy:
    container_name: apache-proxy
    hostname:  apache-proxy
    domainname: wt6.ephec-ti.be
    image: docknux/woodytoys-apache-proxy
    volumes:
      - /etc/letsencrypt:/var/letsencrypt:ro
      - /srv/docker/apache/logs:/usr/local/apache2/logs:rw
      - /etc/localtime:/etc/localtime:ro
    networks:
      production:
        ipv4_address: 10.40.0.10
    restart: always
  www:
    container_name: www
    hostname: www
    domainname: wt6.ephec-ti.be
    image: docknux/woodytoys-www
    volumes:
      - /etc/localtime:/etc/localtime:ro
    networks:
      production:
        ipv4_address: 10.40.0.11
    restart: always
  b2b:
    container_name: b2b
    hostname: b2b
    domainname: wt6.ephec-ti.be
    image: docknux/woodytoys-b2b
    volumes:
      - /etc/localtime:/etc/localtime:ro
    networks:
      production:
        ipv4_address: 10.40.0.12
    restart: always
  db:
    container_name: db
    hostname: db
    domainname: wt6.ephec-ti.be
    image: mysql
    environment:
      - MYSQL_USER=b2b
      - MYSQL_PASSWORD=b2b
      - MYSQL_DATABASE=b2b
      - MYSQL_ROOT_PASSWORD=true
    volumes:
      - /srv/docker/db/data:/var/lib/mysql:rw
      - /srv/docker/db/logs:/var/log/mysql:rw
      - /etc/localtime:/etc/localtime:ro
    networks:
      production:
        ipv4_address: 10.40.0.13
    restart: always

  mail:
    container_name: mail
    hostname: mail
    domainname: wt6.ephec-ti.be
    image: tvial/docker-mailserver:latest
    environment:
      - ENABLE_SPAMASSASSIN=1
      - ENABLE_CLAMAV=1
      - ENABLE_POSTGREY=1
      - ONE_DIR=1
    volumes:
      - ./mail/config:/tmp/docker-mailserver:rw
      - /srv/docker/mail/data:/var/mail:rw
      - /srv/docker/mail/state:/var/mail-state:rw
      - /etc/localtime:/etc/localtime:ro
    networks:
      production:
        ipv4_address: 10.40.0.20
    restart: always

  # DNS
  extern-dns-cache:
    container_name: extern-dns-cache
    hostname: extern-dns-cache
    domainname: wt6.ephec-ti.be
    image: docknux/woodytoys-bind
    volumes:
      - ./bind/configFiles/extern-dns-cache/etc/named.conf:/etc/bind/named.conf:ro
      - /srv/docker/bind/logs/extern-dns-cache:/var/log/bind:rw
      - /etc/localtime:/etc/localtime:ro
    networks:
      dns:
        ipv4_address: 10.50.0.5
    restart: always
  extern-dns-soa:
    container_name: extern-dns-soa
    hostname: extern-dns-soa
    domainname: wt6.ephec-ti.be
    image: docknux/woodytoys-bind
    volumes:
      - ./bind/configFiles/extern-dns-soa/etc/named.conf:/etc/bind/named.conf:ro
      - ./bind/configFiles/extern-dns-soa/var/db.wt6.ephec-ti.be:/var/bind/db.wt6.ephec-ti.be:ro
      - /srv/docker/bind/logs/extern-dns-soa:/var/log/bind:rw
      - /etc/localtime:/etc/localtime:ro
    networks:
      dns:
        ipv4_address: 10.50.0.6
    restart: always

  # LAN
  local-dns-cache:
    container_name: local-dns-cache
    hostname: local-dns-cache
    domainname: wt6.ephec-ti.be
    image: docknux/woodytoys-bind
    volumes:
      - ./bind/configFiles/local-dns-cache/etc/named.conf:/etc/bind/named.conf:ro
      - /srv/docker/bind/logs/local-dns-cache:/var/log/bind:rw
      - /etc/localtime:/etc/localtime:ro
    dns: 10.0.0.5
    networks:
      lan:
        ipv4_address: 10.0.0.5
    restart: always
  squid:
    container_name: squid
    hostname: squid
    domainname: wt6.ephec-ti.be
    image: docknux/woodytoys-squid
    volumes:
      - ./squid/configFiles/squid.conf:/etc/squid3/squid.conf:ro
      - ./squid/configFiles/denydomain:/etc/squid3/denydomain:ro
      - /srv/docker/squid/cache:/var/spool/squid3:rw
      - /srv/docker/squid/logs:/var/log/squid3:rw
      - /etc/localtime:/etc/localtime:ro
    dns: 10.0.0.5
    networks:
      lan:
        ipv4_address: 10.0.0.10
    restart: always
  intranet:
    container_name: intranet
    hostname: intranet
    domainname: wt6.ephec-ti.be
    image: docknux/woodytoys-intranet
    volumes:
      - /etc/localtime:/etc/localtime:ro
    dns: 10.0.0.5
    networks:
      lan:
        ipv4_address: 10.0.0.15
    restart: always
  employee-1:
    container_name: employee-1
    hostname: employee-1
    domainname: wt6.ephec-ti.be
    image: docknux/woodytoys-desktop
    volumes:
      - /etc/localtime:/etc/localtime:ro
    dns: 10.0.0.5
    networks:
      lan:
        ipv4_address: 10.0.0.42
    restart: always
  admin-1:
    container_name: admin-1
    hostname: admin-1
    domainname: wt6.ephec-ti.be
    image: docknux/woodytoys-desktop
    volumes:
      - /etc/localtime:/etc/localtime:ro
    dns: 10.0.0.5
    networks:
      lan:
        ipv4_address: 10.0.0.80
    restart: always

networks:
  lan:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/23
  production:
    driver: bridge
    ipam:
      config:
        - subnet: 10.40.0.0/24
  dns:
    driver: bridge
    ipam:
      config:
        - subnet: 10.50.0.0/24
